---
- name: Create home directory layout
  file: path=/home/{{ user.name }}/{{ item }} state=directory mode=0755
  become: yes
  become_user: "{{ user.name }}"
  with_items: "{{ home_layout }}"
  tags:
    - home
