---
- name: Copy pacman configuration file
  copy: src=pacman.conf dest=/etc/pacman.conf

- name: Refresh pacman mirrors
  pacman: update_cache=yes

- name: Install reflector
  pacman: name=reflector state=present

- name: Sort mirror by reflector
  shell: reflector --latest 50 --age 24 --sort rate --save /etc/pacman.d/mirrorlist

- name: Install core utils packages
  pacman: name={{ core_utils }} state=present
  tags:
    - packages
    - core_utils

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks
        state=directory
  tags:
    - packages

- name: Push pacman mirror list update hook
  copy: src=mirrorupgrade.hook dest=/etc/pacman.d/hooks/mirrorupgrade.hook
  tags:
    - packages

- name: Use all cores when compressing packages
  lineinfile: dest=/etc/makepkg.conf regexp="^COMPRESSXZ" line="COMPRESSXZ=(xz -c -z - --threads=0)"
