---
- name: Install sudo package
  pacman: name=sudo state=present
  tags:
    - user

- name: Copy sudo configuration
  copy: src=sudoers dest=/etc/sudoers mode=0440 validate='visudo -cf %s'
  tags:
    - user
